version: '3.8'
services:
  dynamodb-local:
    # Con este comando se activa la base de datos en el contenedor
    command: "-jar DynamoDBLocal.jar -sharedDb"
    # Se descarga la imagen de base de datos local DynamoDB
    image: "amazon/dynamodb-local:latest"
    # Se agrega un nombre para reconocer este contenedor ya que con este nombre
    # se llamara desde el contendor de la app-python
    hostname: dynamodb-local
    # Se nombra este contenedor
    container_name: dynamodb-local
    # El servicio correra tanto dentro del contenedor como fuera de el por el puerto 8000
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal

  app-python:
    image: prueba30:latest
    container_name: app-python
    ports:
      - "4000:4000"
    # Esta imagne prueba30 se contruyo previamente con el archivo Dockerfile y depende de dynamodb-local
    depends_on:
      - "dynamodb-local"
    links:
      - "dynamodb-local"
    # Se agrega el valor a las variables de entorno correspondientes para acceder
    # a la base de datos DynamoDB que aunque se encuentra local, necesita de aws client
    environment:
      AWS_ACCESS_KEY_ID: '####################'
      AWS_SECRET_ACCESS_KEY: '#########################################'
      DEFAULT_REGION_NAME: '########'


